version: '3.8'

services:
  pdf-to-img:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      - ENV=development
      - PORT=8080
    networks:
      - pdf-to-img-network

networks:
  pdf-to-img-network:
    driver: bridge